Fix handling of border-radius with only one value (MDL-61496)
moodlehq/rtlcss-php pull request #4
Opened 2022-01-20 16:52 UTC by timhunt

This was breaking RTL in the OU theme. This fix works there. Because of issue #3, I cannot easily add a unit test (but I would if the tests passed).

Anyway, please could this be merged (along with the other pull request that has been sitting around for months.

Then, please, could this library be updated in Moodle core - these are bug fixes, so should be done on all stable branches.

2022-01-20 16:52 UTC, timhunt commented
By the way Diff easier to read if you ignore space changes.

2022-01-20 16:56 UTC, timhunt commented
For reference, before this fix, the error message was

```
Exception - Call to undefined method Sabberworm\CSS\Value\Size::getListComponents()

Stack trace:

    line 273 of \lib\rtlcss\RTLCSS.php: Error thrown
    line 223 of \lib\rtlcss\RTLCSS.php: call to MoodleHQ\RTLCSS\RTLCSS->processRule()
    line 55 of \lib\classes\rtlcss.php: call to MoodleHQ\RTLCSS\RTLCSS->processDeclaration()
    line 192 of \lib\rtlcss\RTLCSS.php: call to core_rtlcss->processDeclaration()
    line 63 of \lib\rtlcss\RTLCSS.php: call to MoodleHQ\RTLCSS\RTLCSS->processBlock()
    line 1859 of \lib\outputlib.php: call to MoodleHQ\RTLCSS\RTLCSS->flip()
    line 1837 of \lib\outputlib.php: call to theme_config->rtlize()
    line 1161 of \lib\outputlib.php: call to theme_config->post_process()
    line 205 of \theme\styles.php: call to theme_config->get_css_content()
    line 171 of \theme\styles.php: call to theme_styles_generate_and_store()
```

2022-01-20 17:02 UTC, timhunt commented
The required unit tests probably look something like https://github.com/timhunt/rtlcss-php/commit/26738978b35e28aca6e310fd75ba7ec360a1ad02, if anyone can get the tests working.

2022-01-21 14:29 UTC, sarjona requested changes

2022-01-21 14:29 UTC, sarjona commented on src/MoodleHQ/RTLCSS/RTLCSS.php
> +                    if ($value instanceof RuleValueList) {
I guess you were planning to use $group instead of $value, right? When using $group, I've been able to confirm the patch is working as expected :-)

2022-01-21 15:03 UTC, timhunt commented on src/MoodleHQ/RTLCSS/RTLCSS.php
> +                    if ($value instanceof RuleValueList) {
Doh! yes. (I originally did this in the OU codebase, then copied and pasted to my Moodel core checkout, and then cloned this repo and copied again.

I must have screwed up one of those copies, and with no unit tests, I could not detect that.

Amended commit pushed now.

2022-01-21 15:04 UTC, timhunt commented
Amended commit pushed. (Also rebased)

2022-01-21 16:36 UTC, sarjona approved these changes
Thanks Tim! Now the patch looks good and it's working as expected so I'm more than happy to merge it!  :-)

2022-01-21 16:37 UTC, merged

2022-01-21 16:46 UTC, timhunt commented
Awesome. Thanks :-)